modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="farsight"
version="1.1.2-1.16.5"
displayName="Farsight"
logoFile="farsight.png"
itemIcon="farsight:spyglass"
authors="HerrBrandstetter"
description='''
Placeholder
'''
[[dependencies.farsight]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"
[[dependencies.farsight]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
