modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="farsight_spyglasses"
version="1.4.2-1.16.5"
displayName="Farsight"
logoFile="farsight.png"
itemIcon="farsight_spyglasses:spyglass"
authors="HerrBrandstetter"
credits="Thanks to Blitzor for providing the What meme sound asset and to Epical for improving the spyglass texture."
description='''
Farsight is a small mod that adds one feature: the Spyglass. Crafted from gold, glass and leather, it gives you access to zooming in a Vanilla friendly way.
'''
[[dependencies.farsight_spyglasses]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"
[[dependencies.farsight_spyglasses]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
[[dependencies.farsight_spyglasses]]
modId="curios"
mandatory=false
versionRange="1.16.5-4.0.5.2,)"
ordering="NONE"
side="BOTH"